spring:
  application:
    name: service-absence
  profiles:
    active: local # Change to 'docker' for Docker environment
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    discovery:
      enabled: false

server:
  port: 9000

student:
  service:
    url: http://localhost:8082 